Added Tests
sshestaka/online-book-store pull request #15
Opened 2023-11-29 22:22 UTC by sshestaka

1. Added test cases for Book and Category entities (repository, service, controller).

<img width="447" alt="Added test cases for Book and Category entities" src="https://github.com/sshestaka/online-book-store/assets/123567653/97afd247-4ad4-4dde-991c-de90df680f6c">

2023-11-30 12:50 UTC, Sanderfuck requested changes
Check coverage for methods and lines

2023-11-30 12:50 UTC, Sanderfuck commented on src/test/java/mate/academy/onlinebookstore/controller/BookControllerTest.java
> +    private ObjectMapper objectMapper = new ObjectMapper();
How it possible??? What about DI?

2023-11-30 12:50 UTC, Sanderfuck commented on src/test/java/mate/academy/onlinebookstore/controller/BookControllerTest.java
> +    protected static MockMvc mockMvc;
Why protected?

2023-11-30 12:50 UTC, Sanderfuck commented on src/test/java/mate/academy/onlinebookstore/controller/BookControllerTest.java
> +                .setCoverImage(requestDto.getCoverImage());
Save it in templates and you can reuse it anywhere

2023-11-30 12:50 UTC, Sanderfuck commented on src/test/java/mate/academy/onlinebookstore/controller/BookControllerTest.java
> +                        .setCoverImage("Black cover image")
Write templates

2023-11-30 12:50 UTC, Sanderfuck commented on src/test/java/mate/academy/onlinebookstore/controller/CategoryControllerTest.java
> +        expected.add(new CategoryDto().setId(3L).setName("Category3").setDescription("Category3"));
Use constants for strings

2023-12-01 18:10 UTC, kozhukhovsky approved these changes

2023-12-02 17:53 UTC, merged