Tests for ShoppingCar and Cart Item.
sshestaka/online-book-store pull request #16
Opened 2023-12-05 20:55 UTC by sshestaka

1. Added test cases for ShoppingCar and Cart Item entities (controller, service and repository).

2023-12-06 15:36 UTC, olekskov requested changes

2023-12-06 15:36 UTC, olekskov commented on src/test/java/mate/academy/onlinebookstore/repository/CartItemRepositoryTest.java
> +    )
SQL Setup is 7 times longer than the test itself.
Combine scripts please

2023-12-06 15:36 UTC, olekskov commented on src/test/java/mate/academy/onlinebookstore/service/CartItemServiceTest.java
> +    }
Please place private service methods after main logic

2023-12-06 15:36 UTC, olekskov commented on src/test/java/mate/academy/onlinebookstore/service/ShoppingCartServiceTest.java
> +    private User getUserTest1() {
same here

2023-12-06 15:36 UTC, olekskov commented on src/test/java/mate/academy/onlinebookstore/service/ShoppingCartServiceTest.java
> +                .setCartItems(List.of(cartItemDto));
Please extract these to separate methods.
Your test is too long

2023-12-06 15:36 UTC, olekskov commented on src/test/java/mate/academy/onlinebookstore/service/ShoppingCartServiceTest.java
> +        ShoppingCart shoppingCart = new ShoppingCart()
same, do something, 70 lines of code for test method makes it harder to read than code itself

2023-12-11 15:32 UTC, Sanderfuck requested changes

2023-12-11 15:32 UTC, Sanderfuck commented on src/test/java/mate/academy/onlinebookstore/controller/BookControllerTest.java
> +                .setCoverImage(updateBookRequestDto.getCoverImage());
You can create templates and reuse them for make more readability code

2023-12-11 15:32 UTC, Sanderfuck commented on src/test/java/mate/academy/onlinebookstore/controller/BookControllerTest.java
> +                .setCoverImage("Test-Cover-Image");
You can make it for all books

2023-12-11 15:32 UTC, Sanderfuck commented on src/test/java/mate/academy/onlinebookstore/controller/CategoryControllerTest.java
> +
Templates

2023-12-11 15:32 UTC, Sanderfuck commented on src/test/java/mate/academy/onlinebookstore/service/ShoppingCartServiceTest.java
> +    }
Make templates

2023-12-12 13:27 UTC, merged