Online book store spring boot security v2
sshestaka/online-book-store pull request #8
Opened 2023-11-01 17:45 UTC by sshestaka

2023-11-01 19:02 UTC, Ivan95kos requested changes
Good job overall!

2023-11-01 19:02 UTC, Ivan95kos commented on src/main/java/mate/academy/onlinebookstore/controller/AuthController.java
> +    public UserLoginResponseDto login(@RequestBody UserLoginRequestDto requestDto) {
```suggestion
    public UserLoginResponseDto login(@RequestBody @Valid UserLoginRequestDto requestDto) {
```

2023-11-01 19:02 UTC, Ivan95kos commented on src/main/java/mate/academy/onlinebookstore/security/JwtAuthenticationFilter.java
> +        }
move the Strings and number to constants

2023-11-01 19:02 UTC, Ivan95kos commented on src/main/java/mate/academy/onlinebookstore/service/UserServiceImpl.java
> +    private void updatedUser(User updatedUser, UpdateUserRequestDto updateUserRequestDto) {
All private methods should be below public methods

2023-11-02 11:11 UTC, kozhukhovsky approved these changes

2023-11-02 12:45 UTC, merged